import { redirect } from "next/navigation";
import Link from "next/link";
import { getTenantContext } from "@/lib/tenant";
import { prisma } from "@/lib/prisma";
import { planningEntityToNumber } from "@/lib/planning-entity-bigint";
import { OutreachInbox } from "./outreach-inbox";
import { getCompanyPlanFeatures } from "@/lib/plan-features";

export const dynamic = "force-dynamic";

export default async function OutreachPage() {
  const ctx = await getTenantContext();
  if (!ctx) redirect("/auth/sign-in");
  const features = getCompanyPlanFeatures(ctx.company);

  if (!features.canUseAutoOutreach) {
    return (
      <div className="mx-auto w-full max-w-3xl overflow-auto px-6 py-10">
        <section className="rounded-2xl border border-zinc-200 bg-white p-8 shadow-sm">
          <p className="text-xs font-semibold uppercase tracking-wider text-zinc-500">
            Agency feature
          </p>
          <h1 className="mt-3 text-2xl font-semibold text-zinc-900">
            Outreach approvals are available on Agency
          </h1>
          <p className="mt-3 text-sm leading-6 text-zinc-600">
            The Outreach inbox reviews drafts generated by the autonomous
            outreach pipeline. Upgrade to Agency to enable auto-drafted letters
            from saved searches.
          </p>
          <Link
            href={features.upgradeHref}
            className="mt-6 inline-flex rounded-full bg-zinc-900 px-5 py-2 text-sm font-semibold text-white hover:bg-zinc-800"
          >
            Review billing options
          </Link>
        </section>
      </div>
    );
  }

  const [approvals, counts] = await Promise.all([
    prisma.agentApproval.findMany({
      where: { companyId: ctx.company.id },
      orderBy: [{ status: "asc" }, { createdAt: "desc" }],
      take: 100,
      include: {
        agentRun: {
          select: { kind: true, model: true, costGbp: true, createdAt: true },
        },
      },
    }),
    prisma.agentApproval.groupBy({
      by: ["status"],
      where: { companyId: ctx.company.id },
      _count: { _all: true },
    }),
  ]);

  return (
    <div className="mx-auto w-full max-w-6xl px-6 py-10 overflow-auto">
      <header className="mb-6">
        <h1 className="text-2xl font-semibold tracking-tight">
          Outreach approvals
        </h1>
        <p className="mt-1 text-sm text-zinc-600">
          Drafts generated by the autonomous outreach pipeline. Review and
          approve to convert them into letters or send approved prospect emails.
        </p>
      </header>
      <OutreachInbox
        canSendProspectEmail={ctx.company.prospectEmailOutreachEnabled}
        initialApprovals={approvals.map((a) => ({
          id: a.id,
          status: a.status,
          kind: a.kind,
          subjectRef: a.subjectRef,
          planningEntity: planningEntityToNumber(a.planningEntity),
          draft: a.draftJson as unknown,
          issues: a.issuesJson as unknown,
          confidence: a.confidence,
          createdAt: a.createdAt.toISOString(),
          model: a.agentRun?.model ?? null,
          costGbp: a.agentRun ? Number(a.agentRun.costGbp) : null,
          sentTo: a.sentTo,
          sentAt: a.sentAt?.toISOString() ?? null,
          sentChannel: a.sentChannel,
        }))}
        counts={Object.fromEntries(
          counts.map((c) => [c.status, c._count._all] as const),
        )}
      />
    </div>
  );
}
